"""
Code Artifacts Database
Tracks all code generated by Saraphina with full provenance, signatures, and lifecycle management.
"""
import hashlib
import json
import time
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from enum import Enum
import sqlite3
from pathlib import Path


class ArtifactStatus(Enum):
    """Lifecycle status of code artifact"""
    PROPOSED = "proposed"
    SANDBOX_TESTING = "sandbox_testing"
    TESTS_PASSED = "tests_passed"
    TESTS_FAILED = "tests_failed"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYED = "deployed"
    ROLLED_BACK = "rolled_back"


class ArtifactType(Enum):
    """Type of code artifact"""
    FUNCTION = "function"
    CLASS = "class"
    MODULE = "module"
    PATCH = "patch"
    TEST = "test"
    BUGFIX = "bugfix"
    FEATURE = "feature"


@dataclass
class CodeArtifact:
    """Code artifact with full metadata"""
    artifact_id: str
    artifact_type: ArtifactType
    code: str
    tests: str
    feature_spec: str
    author: str  # "saraphina-ai" or human username
    provenance: Dict[str, Any]  # How it was generated
    signature: str  # SHA-256 hash for integrity
    status: ArtifactStatus
    
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    
    # Static analysis results
    static_analysis: Dict[str, Any] = field(default_factory=dict)
    
    # Test results
    test_results: Dict[str, Any] = field(default_factory=dict)
    coverage_percent: float = 0.0
    
    # Approval tracking
    approved_by: Optional[str] = None
    approved_at: Optional[float] = None
    rejection_reason: Optional[str] = None
    
    # Deployment tracking
    deployed_at: Optional[float] = None
    deployment_target: Optional[str] = None
    
    # Metrics
    execution_count: int = 0
    error_count: int = 0
    success_rate: float = 0.0


class CodeArtifactDB:
    """Database for managing code artifacts"""
    
    def __init__(self, db_path: str = "data/code_artifacts.db"):
        self.db_path = db_path
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        self._init_db()
    
    def _init_db(self):
        """Initialize database schema"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Main artifacts table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS artifacts (
                artifact_id TEXT PRIMARY KEY,
                artifact_type TEXT NOT NULL,
                code TEXT NOT NULL,
                tests TEXT NOT NULL,
                feature_spec TEXT NOT NULL,
                author TEXT NOT NULL,
                provenance TEXT NOT NULL,
                signature TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                static_analysis TEXT,
                test_results TEXT,
                coverage_percent REAL DEFAULT 0.0,
                approved_by TEXT,
                approved_at REAL,
                rejection_reason TEXT,
                deployed_at REAL,
                deployment_target TEXT,
                execution_count INTEGER DEFAULT 0,
                error_count INTEGER DEFAULT 0,
                success_rate REAL DEFAULT 0.0
            )
        """)
        
        # Audit log for all changes
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS artifact_audit_log (
                log_id INTEGER PRIMARY KEY AUTOINCREMENT,
                artifact_id TEXT NOT NULL,
                action TEXT NOT NULL,
                actor TEXT NOT NULL,
                timestamp REAL NOT NULL,
                details TEXT,
                FOREIGN KEY (artifact_id) REFERENCES artifacts(artifact_id)
            )
        """)
        
        # Index for fast lookups
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_status ON artifacts(status)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_author ON artifacts(author)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_created_at ON artifacts(created_at)
        """)
        
        conn.commit()
        conn.close()
    
    def create_artifact(self, artifact: CodeArtifact) -> str:
        """Store new code artifact"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            INSERT INTO artifacts (
                artifact_id, artifact_type, code, tests, feature_spec,
                author, provenance, signature, status, created_at, updated_at,
                static_analysis, test_results, coverage_percent
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            artifact.artifact_id,
            artifact.artifact_type.value,
            artifact.code,
            artifact.tests,
            artifact.feature_spec,
            artifact.author,
            json.dumps(artifact.provenance),
            artifact.signature,
            artifact.status.value,
            artifact.created_at,
            artifact.updated_at,
            json.dumps(artifact.static_analysis),
            json.dumps(artifact.test_results),
            artifact.coverage_percent
        ))
        
        # Audit log
        self._log_action(cursor, artifact.artifact_id, "created", artifact.author, {
            "type": artifact.artifact_type.value,
            "feature_spec": artifact.feature_spec
        })
        
        conn.commit()
        conn.close()
        
        return artifact.artifact_id
    
    def get_artifact(self, artifact_id: str) -> Optional[CodeArtifact]:
        """Retrieve artifact by ID"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("SELECT * FROM artifacts WHERE artifact_id = ?", (artifact_id,))
        row = cursor.fetchone()
        conn.close()
        
        if not row:
            return None
        
        return self._row_to_artifact(row)
    
    def update_status(self, artifact_id: str, status: ArtifactStatus, actor: str, 
                     details: Optional[Dict] = None):
        """Update artifact status"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            UPDATE artifacts 
            SET status = ?, updated_at = ?
            WHERE artifact_id = ?
        """, (status.value, time.time(), artifact_id))
        
        self._log_action(cursor, artifact_id, f"status_changed_to_{status.value}", actor, details)
        
        conn.commit()
        conn.close()
    
    def update_test_results(self, artifact_id: str, test_results: Dict, coverage: float):
        """Update test results and coverage"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            UPDATE artifacts 
            SET test_results = ?, coverage_percent = ?, updated_at = ?
            WHERE artifact_id = ?
        """, (json.dumps(test_results), coverage, time.time(), artifact_id))
        
        conn.commit()
        conn.close()
    
    def approve(self, artifact_id: str, approved_by: str) -> bool:
        """Approve artifact for deployment"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        now = time.time()
        
        cursor.execute("""
            UPDATE artifacts 
            SET status = ?, approved_by = ?, approved_at = ?, updated_at = ?
            WHERE artifact_id = ? AND status = ?
        """, (
            ArtifactStatus.APPROVED.value,
            approved_by,
            now,
            now,
            artifact_id,
            ArtifactStatus.AWAITING_APPROVAL.value
        ))
        
        if cursor.rowcount > 0:
            self._log_action(cursor, artifact_id, "approved", approved_by, None)
            conn.commit()
            conn.close()
            return True
        
        conn.close()
        return False
    
    def reject(self, artifact_id: str, rejected_by: str, reason: str):
        """Reject artifact"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            UPDATE artifacts 
            SET status = ?, rejection_reason = ?, updated_at = ?
            WHERE artifact_id = ?
        """, (ArtifactStatus.REJECTED.value, reason, time.time(), artifact_id))
        
        self._log_action(cursor, artifact_id, "rejected", rejected_by, {"reason": reason})
        
        conn.commit()
        conn.close()
    
    def mark_deployed(self, artifact_id: str, deployment_target: str):
        """Mark artifact as deployed"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        now = time.time()
        
        cursor.execute("""
            UPDATE artifacts 
            SET status = ?, deployed_at = ?, deployment_target = ?, updated_at = ?
            WHERE artifact_id = ?
        """, (ArtifactStatus.DEPLOYED.value, now, deployment_target, now, artifact_id))
        
        self._log_action(cursor, artifact_id, "deployed", "system", {
            "target": deployment_target
        })
        
        conn.commit()
        conn.close()
    
    def list_artifacts(self, status: Optional[ArtifactStatus] = None, 
                      author: Optional[str] = None, limit: int = 50) -> List[CodeArtifact]:
        """List artifacts with optional filters"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        query = "SELECT * FROM artifacts WHERE 1=1"
        params = []
        
        if status:
            query += " AND status = ?"
            params.append(status.value)
        
        if author:
            query += " AND author = ?"
            params.append(author)
        
        query += " ORDER BY created_at DESC LIMIT ?"
        params.append(limit)
        
        cursor.execute(query, params)
        rows = cursor.fetchall()
        conn.close()
        
        return [self._row_to_artifact(row) for row in rows]
    
    def get_audit_log(self, artifact_id: str) -> List[Dict]:
        """Get audit log for artifact"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            SELECT action, actor, timestamp, details
            FROM artifact_audit_log
            WHERE artifact_id = ?
            ORDER BY timestamp DESC
        """, (artifact_id,))
        
        logs = []
        for row in cursor.fetchall():
            logs.append({
                "action": row[0],
                "actor": row[1],
                "timestamp": row[2],
                "details": json.loads(row[3]) if row[3] else None
            })
        
        conn.close()
        return logs
    
    def update_metrics(self, artifact_id: str, execution_success: bool):
        """Update execution metrics"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute("""
            SELECT execution_count, error_count FROM artifacts
            WHERE artifact_id = ?
        """, (artifact_id,))
        
        row = cursor.fetchone()
        if row:
            exec_count = row[0] + 1
            error_count = row[1] + (0 if execution_success else 1)
            success_rate = (exec_count - error_count) / exec_count if exec_count > 0 else 0
            
            cursor.execute("""
                UPDATE artifacts
                SET execution_count = ?, error_count = ?, success_rate = ?
                WHERE artifact_id = ?
            """, (exec_count, error_count, success_rate, artifact_id))
        
        conn.commit()
        conn.close()
    
    def _log_action(self, cursor, artifact_id: str, action: str, actor: str, details: Optional[Dict]):
        """Log action to audit trail"""
        cursor.execute("""
            INSERT INTO artifact_audit_log (artifact_id, action, actor, timestamp, details)
            VALUES (?, ?, ?, ?, ?)
        """, (artifact_id, action, actor, time.time(), json.dumps(details) if details else None))
    
    def _row_to_artifact(self, row) -> CodeArtifact:
        """Convert database row to CodeArtifact"""
        return CodeArtifact(
            artifact_id=row[0],
            artifact_type=ArtifactType(row[1]),
            code=row[2],
            tests=row[3],
            feature_spec=row[4],
            author=row[5],
            provenance=json.loads(row[6]),
            signature=row[7],
            status=ArtifactStatus(row[8]),
            created_at=row[9],
            updated_at=row[10],
            static_analysis=json.loads(row[11]) if row[11] else {},
            test_results=json.loads(row[12]) if row[12] else {},
            coverage_percent=row[13] or 0.0,
            approved_by=row[14],
            approved_at=row[15],
            rejection_reason=row[16],
            deployed_at=row[17],
            deployment_target=row[18],
            execution_count=row[19] or 0,
            error_count=row[20] or 0,
            success_rate=row[21] or 0.0
        )


def compute_signature(code: str, tests: str) -> str:
    """Compute SHA-256 signature for code integrity"""
    content = f"{code}\n---\n{tests}".encode()
    return hashlib.sha256(content).hexdigest()
